//这段由李雅琪和张佳微完成后写入
const replaceKeyWordMap=new Map([
    
        ["abstract","C_1 C_3 C_5"],
        ["arguments","C_2 C_4 C_6"],
        ["boolean","C_3 C_5 C_7"],
        ["break","C_4 C_6 C_1"],
        ["byte","C_5 C_7 C_2"],
        ["case","C_6 C_1 C_3"],
        ["catch","C_7 C_2 C_4"],
        ["char","D_1 D_3 D_5"],
        ["class*","D_2 D_4 D_6"],
        ["const","D_3 D_7 D_5"],
        ["continue","D_4 D_6 D_1"],
        ["debugger","D_5 D_7 D_2"],
        ["default","D_6 D_1 D_3"],
        ["delete","D_7 D_2 D_4"],
        ["do","E_1 E_3 E_5"],
        ["double","E_2 E_4 E_6"],
        ["else","E_3 E_5 E_7"],
        ["enum*","E_4 E_6 E_1"],
        ["eval","E_5 E_7 E_2"],
        ["export*","E_6 E_1 E_3"],
        ["extends*","E_7 E_2 E_4"],
        ["false","F_1 F_3 F_5"],
        ["final","F_2 F_4 F_6"],
        ["finally","F_3 F_5 F_7"],
        ["float","F_4 F_6 F_1"],
        ["for","F_5 F_7 F_2"],
        ["function","F_6 F_1 F_3"],
        ["goto","F_7 F_2 F_4"],
        ["if","A_1 A_3 A_5"],
        ["implements","A_2 A_4 A_6"],
        ["import*","A_3 A_5 A_7"],
        ["in","A_4 A_6 A_1"],
        ["instanceof","A_5 A_7 A_2"],
        ["int","A_6 A_1 A_3"],
        ["interface","A_7 A_2 A_4"],
        ["let","C_2 C_4 C_6 C_1"],
        ["long","C_3 C_5 C_7 C_2"],
        ["native","C_5 C_7 C_2 C_4"],
        ["new","C_6 C_1 C_3 C_5"],
        ["null","D_2 D_4 D_6 D_1"],
        ["package","D_3 D_5 D_7 D_2"],
        ["private","D_5 D_7 D_2 D_4"],
        ["protected","D_6 D_1 D_3 D_5"],
        ["public","E_2 E_4 E_6 E_1"],
        ["return","E_3 E_5 E_7 E_2"],
        ["short","E_5 E_7 E_2 E_4"],
        ["static","E_6 E_1 E_3 E_5"],
        ["super*","F_2 F_4 F_6 F_1"],
        ["switch","F_3 F_5 F_7 F_2"],
        ["synchronized","F_5 F_7 F_2 F_4"],
        ["this","F_6 F_1 F_3 F_5"],
        ["throw","A_2 A_4 A_6 A_1"],
        ["throws","A_3 A_5 A_7 A_2"],
        ["transient","A_5 A_7 A_2 A_4"],
        ["ture","A_6 A_1 A_3 A_5"],
        ["try","C_1 C_3 C_5 C_6#b7"],
        ["typeof","D_1 D_3 D_5 D_7"],
        ["var","E_1 E_3 E_5 E_6#b7"],
        ["void","F_1 F_3 F_5 F_6#b7"],
        ["while","A_1 A_3 A_5#b7"]
        
])
export default replaceKeyWordMap